version: "3.7"

volumes:
  postgres-local:

services:
  web: 
    build: ./my-app
    command: yarn start
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on: 
      - api
  api: 
    build: ./api
    command: ['yarn' ,'production']
    environment: 
      - HOST=db
    ports:
      - "5000:5000"
    depends_on: 
      - db
  db:
    image: postgres:11.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=chat
      - POSTGRES_PASSWORD=chat
      - POSTGRES_DB=db_chat
    volumes:
      - postgres-local:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    restart: on-failure
    ports:
      - 5433:8081
    environment:
      - DATABASE_URL=postgres://chat:chat@db:5432/db_chat?sslmode=disable
    depends_on:
      - db
    healthcheck:
      disable: true
